# Generated by Django 5.0.6 on 2025-12-12 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="widget",
            name="display_type",
            field=models.CharField(
                choices=[
                    ("gauge", "Gauge Type"),
                    ("chart", "Chart Type"),
                    ("map", "Map Type"),
                    ("slider", "Slider Type"),
                    ("switch", "Switch Type"),
                    ("value", "Value Type"),
                    ("histogram", "Histogram Type"),
                    ("table", "Table Type"),
                ],
                default="gauge",
                max_length=256,
            ),
        ),
        migrations.AddField(
            model_name="widget",
            name="entity_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="width",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="widget",
            name="y",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="widget",
            name="configuration",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="widget",
            name="dashboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_widgets",
                to="dashboard.dashboard",
            ),
        ),
    ]
