# Generated by Django 5.0.6 on 2024-11-20 07:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("space", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyDeviceState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("state_name", models.CharField(max_length=256)),
                ("device_slug_name", models.SlugField(max_length=256)),
                ("value", models.DecimalField(decimal_places=10, max_digits=19)),
                ("from_timestamp", models.DateTimeField()),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="space.space"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HourlyDeviceState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("state_name", models.CharField(max_length=256)),
                ("device_slug_name", models.SlugField(max_length=256)),
                ("value", models.DecimalField(decimal_places=10, max_digits=19)),
                ("from_timestamp", models.DateTimeField()),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="space.space"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MinutelyDeviceState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("state_name", models.CharField(max_length=256)),
                ("device_slug_name", models.SlugField(max_length=256)),
                ("value", models.DecimalField(decimal_places=10, max_digits=19)),
                ("from_timestamp", models.DateTimeField()),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="space.space"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MonthlyDeviceState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("state_name", models.CharField(max_length=256)),
                ("device_slug_name", models.SlugField(max_length=256)),
                ("value", models.DecimalField(decimal_places=10, max_digits=19)),
                ("from_timestamp", models.DateTimeField()),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="space.space"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
