# Generated by Django 4.2.15 on 2024-08-15 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("space", "0002_remove_space_is_multi_tenant_space_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyDeviceState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("state_name", models.CharField(max_length=256)),
                ("device_slug_name", models.SlugField(max_length=256)),
                ("value", models.DecimalField(decimal_places=10, max_digits=19)),
                ("from_timestamp", models.DateTimeField()),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="space.space"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MinutelyDeviceState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("state_name", models.CharField(max_length=256)),
                ("device_slug_name", models.SlugField(max_length=256)),
                ("value", models.DecimalField(decimal_places=10, max_digits=19)),
                ("from_timestamp", models.DateTimeField()),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="space.space"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HourlyDeviceState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("state_name", models.CharField(max_length=256)),
                ("device_slug_name", models.SlugField(max_length=256)),
                ("value", models.DecimalField(decimal_places=10, max_digits=19)),
                ("from_timestamp", models.DateTimeField()),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="space.space"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DailyDeviceState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("state_name", models.CharField(max_length=256)),
                ("device_slug_name", models.SlugField(max_length=256)),
                ("value", models.DecimalField(decimal_places=10, max_digits=19)),
                ("from_timestamp", models.DateTimeField()),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="space.space"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
